// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.0
//   protoc               v3.14.0
// source: proto/todo.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "todo";

/** message it's basicly interface or type! */
export interface Todo {
  /** 1 2 3 just an order not a value */
  id: number;
  description: string;
  isDone: boolean;
}

export interface Todos {
  /** same (repeated) Todo but many */
  Todos: Todo[];
}

export interface PostTodoDTO {
  description: string;
  isDone: boolean;
}

export interface Empty {
}

export const TODO_PACKAGE_NAME = "todo";

/** buissnes logic */

export interface TodoServiceClient {
  postTodo(request: PostTodoDTO): Observable<Todo>;

  getTodos(request: Empty): Observable<Todos>;
}

/** buissnes logic */

export interface TodoServiceController {
  postTodo(request: PostTodoDTO): Promise<Todo> | Observable<Todo> | Todo;

  getTodos(request: Empty): Promise<Todos> | Observable<Todos> | Todos;
}

export function TodoServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["postTodo", "getTodos"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("TodoService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("TodoService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const TODO_SERVICE_NAME = "TodoService";
